### PR TITLE
Add support for Linux

### PR DESCRIPTION
**Pull request by marian-bielcik**
Hi Cherno,
I added support for Linux in the "premake5.lua" file.

Thanks.
Marian

### CODE REVIEW

**Comment by Gaztin** [comment]
It looks like you changed the indentation method from tabs to spaces. It makes it a little tough to read the diff.

**Comment by DaveAxiom** [comment]
@Gaztin This PR is 6 months old and changes formatting months before tabs were recommended in the Game Engine video series. Can this just be accepted?

**Comment by Gaztin** [comment]
It's not about which style is recommended. This PR will mix tab and space indentations, and that is a bad practice.
Ultimately, though, it's up to Cherno.

**Comment by DaveAxiom** [comment]
It will take another Pull Request to fix the formatting regardless! There is a lot more work that is dependent on the IMGUI PR and this PR.

**Comment by Gaztin** [comment]
Why would it take another PR to fix the formatting?

**Comment by DaveAxiom** [comment]
I guess `git commit --amend` would fix a released commit???
https://ohshitgit.com/

My experience with Github is that it takes months for contributors or repository owners to respond.

**Comment by Gaztin** [comment]
You can keep pushing commits to a PR after you created it.

**Comment by LovelySanta** [comment]
> It looks like you changed the indentation method from tabs to spaces. It makes it a little tough to read the diff.

It was a mix of tabs and spaces and @marian-bielcik converted to spaces.
I aggree to convert it all to tabs as cherno wants.

**Pull request closed without merging**
